@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters "star CLIENT_INDEX";
:Model#getFilteredPersonList();

if (Index out of bounds?) then (yes)
    :Throw CommandException\n("Invalid person displayed index");
    stop
else (no)
    :Retrieve Person at CLIENT_INDEX;
    if (Person already starred?) then (yes)
        :Throw CommandException\n("Chosen client is already starred");
        stop
    else (no)
        :Rebuild Person with isStarred = true;
        :Model#setPerson(oldPerson, newPerson);
        :Model#sortPersons(STARRED_STATUS_COMPARATOR);
        :Model#refreshFilteredPersonList();
        :Return success message;
    endif
endif
stop
@enduml
